### ISSUE TITLE
Various possible data sources

### ISSUE THREAD

**Issue by sckott** [ropensci/ots#18]
- [x] http://imars.marine.usf.edu/CAR/  - sep issue
- [ ] http://ijgofs.whoi.edu/Time-Series/LTTS.html
- [x] http://www.oceansites.org/data/index.html  - sep issue
- [x] ftp://ftp.pmel.noaa.gov/ -  sep issue
- [x] http://uop.whoi.edu/projects/Stratus/stratusdata.html  - sep issue
- [x] http://imos.org.au/home.html - don't think we can use this
- [ ] big list of potential data sources http://www.ocean-partners.org/ocean-observations/long-term-datasets

**Comment by remsamp** [comment]
Scott, thanks for doing that, this will be an incredibly useful package. I am not sure whether this is something you have already considered but for physics there is also:

http://www.marine-geo.org/tools/web_services.php#gmrt 
http://www.marspec.org/Modern_Data.html
http://www.metoffice.gov.uk/hadobs/hadisst/data/download.html

**Comment by sckott** [comment]
thanks for the links!  

glad to hear it could be useful :) gives me more motivation to work on it
