### ISSUE TITLE
users?

### ISSUE THREAD

**Issue by sckott** [ropensci/ots#25]
Does anyone use this?  Curious if should put more time into this, and if so, to put on CRAN  @jebyrnes

**Comment by jebyrnes** [comment]
I'm not sure how many folk know about it.  Hrm.  What is a better way to get the word out?

**Comment by sckott** [comment]
Hmm.  I'll think about it tomorrow

**Comment by sckott** [comment]
Asked folks on our forum https://discuss.ropensci.org/t/anyone-for-ocean-time-series-data/256 with a poll - not sure if we'll get enough answers to be meaningful.

**Comment by sckott** [comment]
thanks @jebyrnes , enough interest to move forward, setting milestone 1 deadline for a few weeks - may change if more to do

**Comment by sckott** [comment]
https://github.com/ropensci/ots/milestones/v0.1

**Comment by jebyrnes** [comment]
Have you thought about a poster or workshop at ASLO, WSN, or Benthics?  Would also go a long way. And/or poster at ITRS. I'm happy to be your shill if you need me.

On Nov 3, 2015, at 6:12 PM, Scott Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/ropensci/ots/milestones/v0.1

-

**Comment by sckott** [comment]
Are these the ones you refer to:

* http://www.bemsociety.org/conference.html
* http://www.itrs11.org/
* http://aslo.org/meetings/
* http://www.wsn-online.org/2015meeting/

**Comment by jebyrnes** [comment]
Yep.
Heading to WSN on Thursday. So not this year, but perhaps next.
BEM is in March. Will be there.

On Nov 3, 2015, at 7:08 PM, Scott Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


Are these the ones you refer to:

  *   http://www.bemsociety.org/conference.html
  *   http://www.itrs11.org/
  *   http://aslo.org/meetings/
  *   http://www.wsn-online.org/2015meeting/

**Comment by sckott** [comment]
Regarding BEM, would you be willing to include `ots` in a talk you're already doing, or something else?

The summer ASLO meeting (June 5-10, 2016) in Santa Fe looks doable for me - is that a good one to go to?

**Comment by jebyrnes** [comment]
Depending on what I talk about at BEM, sure!  I don’t know what I’m going to do there yet. Alternately, might there be a standard poster?

On Nov 4, 2015, at 10:59 AM, Scott Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


Regarding BEM, would you be willing to include ots in a talk you're already doing, or something else?

The summer ASLO meeting (June 5-10, 2016) in Santa Fe looks doable for me - is that a good one to go to?

**Comment by sckott** [comment]
There could be a poster. We do have one cheatsheet https://github.com/ropensci/cheatsheets/blob/master/taxize/taxize-cheatsheet.jpg and plan to make more. So making a poster could be combined with making a cheatsheet - If it makes more sense for the meeting, we could do a poster of `ots` + other ropensci pkgs that make sense (e.g., `rfishbase`)

**Comment by jebyrnes** [comment]
That would be fantastic. Happy to put that in for any meeting I head to!

On Nov 4, 2015, at 12:12 PM, Scott Chamberlain <notifications@github.com<mailto:notifications@github.com>> wrote:


There could be a poster. We do have one cheatsheet https://github.com/ropensci/cheatsheets/blob/master/taxize/taxize-cheatsheet.jpg and plan to make more. So making a poster could be combined with making a cheatsheet - If it makes more sense for the meeting, we could do a poster of ots + other ropensci pkgs that make sense (e.g., rfishbase)

**Comment by sckott** [comment]
cool, sounds good
